config/routes.rb
Rails.application.routes.draw do
root 'top#index'  
get '/linead', to: 'top#linead'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
    def index
        
    end
    
    def linead
        
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.erb
<!-- footer -->
<div class="row text-center">
  <ul>
    <h6>Copyright © 2016 citygift</h6>
  </ul>
</div>
<!-- footer -->

app/views/layouts/_header.html.erb
<!-- navigation -->
<div class="top-bar">
    <div class="top-bar-title">  
        <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
            <button class="menu-icon dark" type="button" data-toggle></button>
        </span>      
        <strong>Citygift</strong>
    </div>
    <div class="top-bar-right">
        <div id="responsive-menu">
            <ul class="dropdown menu" data-dropdown-menu>
                
                <li><%= link_to "Home", root_path %></li>
                <li class="toplink"><%= link_to "Service", root_path(anchor: 'service'), data: { no_turbolink: true } %></li>
                <li>
                    <a href="#">Area</a>
<!--area直接飛べるようにしてから
                    <ul class="menu">
                      <li class="topdown"><a href="#">Item 1A</a></li>
                      <li class="topdown"><a href="#">Item 1A</a></li>
                      <li class="topdown"><a href="#">Item 1A</a></li>
                      <li class="topdown"><a href="#">Item 1A</a></li>
                      <li class="topdown"><a href="#">Item 1A</a></li>
                    </ul>
-->
                </li>
              <li><a href="#">Contact</a></li>
            </ul>         
        </div>
    </div>
</div>
<!-- navigation -->

app/views/layouts/_ogp.html.erb
<!--ogp-->
    <meta property="og:title" content="Citygift公式" />
    <meta property="og:type" content="ページの種類" />
    <meta property="og:url" content="ページのURL" />
    <meta property="og:image" content="サムネイル画像のURL" />
    <meta property="og:site_name" content="Citygift" />
    <meta property="og:description" content="街歩きをもっと豊かにしてくれるサービスです。" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Citygift" %></title>
    
    
    <%= render 'layouts/ogp' %>
    
    <%= favicon_link_tag('favicon.png') %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/index/_area.html.erb
<!-- area -->
<div class="row">
  <div class="large-12 columns">
  <h2 style="margin: 0;" class="text-center">Area</h2>
  <h6 style="margin: 0;" class="text-center">地域からプランを探す</h6>
    <br>
    <br>
    <div class="row">
    <div class="small-12 medium-10 medium-centered columns">
      <div class="medium-8 columns">
        <p><%= image_tag("tokyo.jpg", alt: "tokyo") %></p>
      </div>
      <div class="medium-4 columns">
        <p><%= image_tag("kamakura.jpg", alt: "kamakura") %></p>
        <p><%= image_tag("onomichi.jpg", alt: "onomichi") %></p>
      </div>
    </div>
    </div>
<!--
    <div class="row">
    <div class="small-12 medium-10 medium-centered columns">
        <div class="medium-4 columns">
            <p><img src="http://placehold.it/400x200&text=Other cool article" alt="article promo image" alt="advertisement for deep fried Twinkies"></p>
            <p><img src="http://placehold.it/400x200&text=Other cool article" alt="article promo image"></p>
        </div>
        <div class="medium-8 columns">
            <p><img src="http://placehold.it/900x450&text=Promoted Article" alt="main article image"></p>
        </div>
    </div>
    </div>
-->
    </div>
</div>
<!-- area -->

app/views/layouts/index/_concept.html.erb
<!-- concept -->
<hr>
<div class="row">
    <div class="large-12 columns">
    <h2 style="margin: 0;" class="text-center">Concept</h2>
    <h6 style="margin: 0;" class="text-center">身近な場所をもっと楽しもう!</h6>
    <br>
    <br>
    <div class="small-8 medium-8 small-centered columns">
        <div class="row text-center">
            <p class="small-12 columns">普段通りすぎてしまう街も、しっかり探すと何か見つかる。そんな体験から『citygift』は生まれました。</p>
            <p class="small-12 columns">どんな街にも素敵なストーリーは存在し、ストーリーは街を魅力的に仕立て上げ、魅力的な街は人生を豊かにしてくれます。</p>
            <p class="small-12 columns">時間が余ったら近くの街を探検しにいく、そんなライフスタイルを私たちは提供します。</p>
        </div>
    </div>
    </div>
</div>
<hr>
<!-- concept -->

app/views/layouts/index/_home.html.erb
<!-- home -->
<div class="expanded rows">
<div id="toppic" class="callout large-12 columns"/>
    <div id="box" class="text-center"> 
        <div>
            <br>
            <br>
            <h1>you can find the beautiful world</h1>
            <p class="lead">街歩き体験サービス『citygift』</p>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <%= link_to "Line add", linead_path,:class => 'button large' %>
            <a href="#" class="button large hollow">LOGIN</a>
            <br>
            <br>          
        </div>
    </div>
</div>
<!-- home -->

app/views/layouts/index/_likeus.html.erb
<!-- likeus -->
<div class="row">
    <div class="large-12 columns">
        <h2 style="margin: 0;" class="text-center">Like us</h2>
        <h6 style="margin: 0;" class="text-center">SNSで最新情報を発信しています</h6>
        <br>
        <br>
        <div class="small-6 medium-6 small-centered columns">
        <div class="row　text-center">
<!--facebook-->
            <div class="medium-3 small-3 columns text-center">
              <i class="fi-social-facebook"></i>
                <div class="small-8 medium-8 small-centered columns">
                    <p><%= image_tag("facebook.png", alt: "facebook") %></p>      
                </div>
              <br>
            </div>
<!--twitter-->
            <div class="medium-3 small-3 columns text-center">
              <i class="fi-social-twitter"></i>
                <div class="small-8 medium-8 small-centered columns">
                    <p><%= image_tag("twitter.png", alt: "twitter") %></p>      
                </div>              
              <br>
            </div>
<!--insta-->
            <div class="medium-3 small-3 columns text-center">
              <i class="fi-social-instagram"></i>
                <div class="small-8 medium-8 small-centered columns">
                    <p><%= image_tag("instagram.png", alt: "instagram") %></p>      
                </div>             
              <br>
            </div>
<!--line-->
            <div class="medium-3 small-3 columns text-center">
              <i class="fi-social-line"></i>
                <div class="small-8 medium-8 small-centered columns">
                    <p><%= image_tag("line.png", alt: "line") %></p>      
                </div>                   
            </div>

        </div>      
        </div>
        
    </div>
</div>
<br>
<!-- likeus -->

app/views/layouts/index/_newplan.html.erb
<!-- newplan -->
<div class="row">
<div class="large-12 columns">
  <h2 style="margin: 0;" class="text-center">LATEST Plan</h2>
  <h6 style="margin: 0;" class="text-center">新着プランから探す</h6>
</div>
</div>
<div class="row">
  <div class="large-12 columns">

  <article>
<br>
<br>
<!-- 最新記事1 -->
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><%= image_tag("omotesando.jpg", alt: "omodetando") %></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">表参道3時間まったりコース</a></h5>
        <p>
          <span><i class="fi-torso"> By Yuta &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 6 comments</i></span>
        </p>
        <p>表参道を原宿方面からまったり歩くコースです。大人のためのお子様ランチを食べ、雑貨屋さんを覗いてからカフェでまったり。息抜きにオススメのプランです。</p>
      </div>
    </div>
<!-- 最新記事2 -->
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><%= image_tag("onomichi.jpg", alt: "onomichi") %></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">尾道3時間わくわくコース</a></h5>
        <p>
          <span><i class="fi-torso"> By Yuta &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 12/3/16 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 4 comments</i></span>
        </p>
        <p>広島の尾道を散策していくコースです。石畳に囲まれた神社を巡って、志賀直哉の暗夜行路を堪能したのちに、尾道ラーメンを食していきます。一人街歩きにおすすめのプランです。</p>
      </div>
    </div>
<!-- 最新記事3 -->
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><%= image_tag("kamakura.jpg", alt: "kamakura") %></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">鎌倉満喫4時間コース</a></h5>
        <p>
          <span><i class="fi-torso"> By Yuta &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 1/14/17 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 8 comments</i></span>
        </p>
        <p>鎌倉の心地良さを満喫するコースです。報国寺や長谷寺をめぐり自然のパワーを存分に吸収できます。ふとした小旅行におすすめのプランです。</p>
      </div>
    </div>
<!-- 最新記事4 -->
<!--
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><img src="http://placehold.it/600x370&text=Look at me!" alt="image for article" alt="article preview image"></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">代々木上原3時間充実コース</a></h5>
        <p>
          <span><i class="fi-torso"> By Yuta &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 1/9/17 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 3 comments</i></span>
        </p>
        <p>代々木上原を満喫するコースです。銭湯に入ってから、立ち飲みワインをいただき、最後においしいディナーで締めるプランです。仲の良い友達の気分転換にオススメのプランです。</p>
      </div>
    </div>
-->
<!-- 最新記事5 -->
<!--
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><img src="http://placehold.it/600x370&text=Look at me!" alt="image for article" alt="article preview image"></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">石神井公園2時間ほのぼのコース</a></h5>
        <p>
          <span><i class="fi-torso"> By Yuta &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 12/19/16 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 4 comments</i></span>
        </p>
        <p>石神井公園を一周巡ってから、駅の近くにあるピザ屋さんで石窯ピザを食べるプランです。晴れた日にオススメのプランです。</p>
      </div>
    </div>
-->
<!-- 最新記事6 -->
<!--
    <div class="large-4 columns">
      <div class="large-12 medium-6 small-12 columns">
        <p><img src="http://placehold.it/600x370&text=Look at me!" alt="image for article" alt="article preview image"></p>
      </div>
      <div class="large-12 medium-6 small-12 columns">
        <h5><a href="#">'Death Star' Vaporizes Its Own Planet</a></h5>
        <p>
          <span><i class="fi-torso"> By Thadeus &nbsp;&nbsp;</i></span>
          <span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
          <span><i class="fi-comments"> 6 comments</i></span>
        </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae impedit beatae, ipsum delectus aperiam nesciunt magni facilis ullam.</p>
      </div>
    </div>
-->

    <hr>
    <div class="row text-center">
      <a class="button hollow expanded text-center">Load More</a>
    </div>
    

    </article>

  </div>
  <hr>
</div> 
<!-- newplan -->

app/views/layouts/index/_news.html.erb
<!-- news -->
<div class="news">
    <div class="small-12 medium-10 medium-centered columns">
    <div class="rows">
        <div class="small-3 columns">
            <h6>NEWS</h6>
        </div>
        <div class="small-9 columns">
        <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
          <ul class="orbit-container">
            <li class="is-active orbit-slide">
              <h6>1/14 卒業制作提出</h6>
            </li>
            <li class="orbit-slide">
              <h6>1/20 Bot機能実装</h6>
            </li>
            <li class="orbit-slide">
              <h6>2/2 GGA出場</h6>
            </li>
            <li class="orbit-slide">
              <h6>2/11 Lineaward エントリー</h6>
            </li>
          </ul>
        </div>
        </div>
    </div>
    </div>   
</div>

<!-- news -->

app/views/layouts/index/_service.html.erb
<!-- service -->
<hr>
<div id="service" class="row">
  <div class="large-12 columns">
  <h2 style="margin: 0;" class="text-center">Service</h2>
  <h6 style="margin: 0;" class="text-center">街歩きを素敵な体験へ</h6>
  <br>
  <br>

  <article>
    
<!-- 左 -->
<div class="large-4 columns text-center">
    <div class="small-10 medium-10 small-centered columns">
        <h4>Friend Request</h4>
        <div class="panel serviceimage">
            <p><%= image_tag("linehome.png", alt: "friend") %></p>
        </div>
    </div>
<br>
</div>
<!-- 中央 -->
<div class="large-4 columns text-center">
    <div class="small-10 medium-10 small-centered columns">
        <h4>Get Plan</h4>
        <div class="panel serviceimage">
            <p><%= image_tag("planstart.png", alt: "planstart") %></p>
            <p><%= image_tag("planget.png", alt: "planstart") %></p>
        </div>       
    </div>
<br>
</div>
<!-- 右 -->
<div class="large-4 columns text-center">
    <div class="small-10 medium-10 small-centered columns">
        <h4>Push Plan</h4>
        <div class="panel serviceimage">
            <p><%= image_tag("unimplimented.png", alt: "planmake") %></p>
        </div>       
    </div>
<br>
</div>
    
    </article>

  </div>
</div>
<hr>
<!-- service -->

app/views/layouts/index/_shortsummary.html.erb
<!-- shortsummary -->
<div class="shortsummary">
<hr>
    <div class="row">
      <div class="medium-6 columns medium-push-6">
        <div class="small-8 medium-8 small-centered columns">
            <div class="text-center">
                <br>
                <%= image_tag 'gift.png', :size => '200x200' %>
                <br>
                <br>
            </div>

        </div>
      </div>
      <div class="medium-6 columns medium-pull-6">
        <h2>What's Citygift?</h2>
        <p>普段通りすぎる日常に再発見を。Citygiftは身近にある街の素敵なプランを共有できるサービスです。時間が空いた時にプランを検索することができたり、偶然素敵な散歩道を見つけたら投稿することができます。<br>まずは友達に追加してみてください。</p>
      </div>
    </div>

    <div class="row">
      <div class="medium-4 columns">
        <h3>入手</h3>
        <p>LINEからCitygiftに向かって話しかけるだけで、あなたに合わせた街歩きプランを提案してくれます。</p>
      </div>
      <div class="medium-4 columns">
        <h3>投稿</h3>
        <p>LINEからCitygiftに向かって写真とコメントを送信することで、あなただけの街歩きプランを作成します。</p>
      </div>
      <div class="medium-4 columns">
        <h3>一覧</h3>
        <p>このページでは皆様から頂いた街歩きプランを紹介しています。街歩きのキュレーションとしてお楽しみください。</p>
      </div>
    </div>
<hr>
</div>
<!-- shortsummary -->

app/views/top/index.html.erb
<!--toppage-->


<!--home-->
<%= render 'layouts/index/home' %>

<!--news-->
<%= render 'layouts/index/news' %>

<!--summary-->
<%= render 'layouts/index/shortsummary' %>

<!--newplan-->
<%= render 'layouts/index/newplan' %>

<!--area-->
<%= render 'layouts/index/area' %>

<!--service-->
<%= render 'layouts/index/service' %>

<!--likeus-->
<%= render 'layouts/index/likeus' %>

<!--concept-->
<%= render 'layouts/index/concept' %>

app/views/top/linead.html.erb
<div class="row">
<div class="large-12 columns">
  <br>
  <h2 style="margin: 0;" class="text-center primary">Citygiftアカウント</h2>
  <h6 style="margin: 0;" class="text-center">以下のQRコードからLineの友達に追加</h6>
</div>
</div>

<div class="small-8 medium-8 small-centered columns">
    <div class="text-center">
        <br>
        <img src="http://qr-official.line.me/L/U_DtPWcVZ7.png">
        <p>
        LINEアプリを起動して、<br>
        ［その他］タブの［友だち追加］でQRコードをスキャンします。
        </p>
    </div>
    <br>
    <br>
</div>

app/views/top/profile.html.erb
<h1>Top#profile</h1>
<p>Find me in app/views/top/profile.html.erb</p>